<a href="https://colab.research.google.com/github/IlyaGolovin/Machine-learning-project/blob/master/Machine_learning_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd 
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

In [2]:
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Micro-credentials classes/Machine Learning Project4/DATA/diabetic_data.csv")

In [3]:
df.head()

   encounter_id  patient_nbr             race  ... change diabetesMed readmitted
0       2278392      8222157        Caucasian  ...     No          No         NO
1        149190     55629189        Caucasian  ...     Ch         Yes        >30
2         64410     86047875  AfricanAmerican  ...     No         Yes         NO
3        500364     82442376        Caucasian  ...     Ch         Yes         NO
4         16680     42519267        Caucasian  ...     Ch         Yes         NO

[5 rows x 50 columns]

In [ ]:
df.info()

In [5]:
df.isnull()

        encounter_id  patient_nbr   race  ...  change  diabetesMed  readmitted
0              False        False  False  ...   False        False       False
1              False        False  False  ...   False        False       False
2              False        False  False  ...   False        False       False
3              False        False  False  ...   False        False       False
4              False        False  False  ...   False        False       False
...              ...          ...    ...  ...     ...          ...         ...
101761         False        False  False  ...   False        False       False
101762         False        False  False  ...   False        False       False
101763         False        False  False  ...   False        False       False
101764         False        False  False  ...   False        False       False
101765         False        False  False  ...   False        False       False

[101766 rows x 50 columns]

In [6]:
df= df.drop(columns=['encounter_id','patient_nbr','weight','admission_type_id','discharge_disposition_id','admission_source_id','payer_code','medical_specialty','number_outpatient','number_inpatient','max_glu_serum','A1Cresult','metformin','repaglinide','nateglinide','chlorpropamide','glimepiride','acetohexamide','glipizide','glyburide','tolbutamide','pioglitazone','rosiglitazone','acarbose','miglitol','troglitazone','tolazamide','examide','citoglipton','glyburide-metformin','glipizide-metformin','glimepiride-pioglitazone',])

In [7]:
df.head()

              race  gender      age  ...  change  diabetesMed  readmitted
0        Caucasian  Female   [0-10)  ...      No           No          NO
1        Caucasian  Female  [10-20)  ...      Ch          Yes         >30
2  AfricanAmerican  Female  [20-30)  ...      No          Yes          NO
3        Caucasian    Male  [30-40)  ...      Ch          Yes          NO
4        Caucasian    Male  [40-50)  ...      Ch          Yes          NO

[5 rows x 18 columns]

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101766 entries, 0 to 101765
Data columns (total 18 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   race                     101766 non-null  object
 1   gender                   101766 non-null  object
 2   age                      101766 non-null  object
 3   time_in_hospital         101766 non-null  int64
 4   num_lab_procedures       101766 non-null  int64
 5   num_procedures           101766 non-null  int64
 6   num_medications          101766 non-null  int64
 7   number_emergency         101766 non-null  int64
 8   diag_1                   101766 non-null  object
 9   diag_2                   101766 non-null  object
 10  diag_3                   101766 non-null  object
 11  number_diagnoses         101766 non-null  int64
 12  insulin                  101766 non-null  object
 13  metformin-rosiglitazone  101766 non-null  object
 14  metformin-pioglitazone   101766 non-null  object
 15  change                   101766 non-null  object
 16  diabetesMed              101766 non-null  object
 17  readmitted               101766 non-null  object
dtypes: int64(6), object(12)
memory usage: 14.0+ MB

In [9]:
df= df.drop(columns=['race','gender','diag_1','diag_2','diag_3','insulin','metformin-rosiglitazone','metformin-pioglitazone','change','diabetesMed','readmitted'])

In [10]:
df.head()

       age  time_in_hospital  ...  number_emergency  number_diagnoses
0   [0-10)                 1  ...                 0                 1
1  [10-20)                 3  ...                 0                 9
2  [20-30)                 2  ...                 0                 6
3  [30-40)                 2  ...                 0                 7
4  [40-50)                 1  ...                 0                 5

[5 rows x 7 columns]

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101766 entries, 0 to 101765
Data columns (total 7 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   age                 101766 non-null  object
 1   time_in_hospital    101766 non-null  int64
 2   num_lab_procedures  101766 non-null  int64
 3   num_procedures      101766 non-null  int64
 4   num_medications     101766 non-null  int64
 5   number_emergency    101766 non-null  int64
 6   number_diagnoses    101766 non-null  int64
dtypes: int64(6), object(1)
memory usage: 5.4+ MB

In [12]:
v1=lambda x:int(x[3:-1])

In [13]:
df.age=df.age.apply(v1)

In [14]:
df.age.dtype

dtype('int64')

In [15]:
from sklearn.preprocessing import StandardScaler

In [16]:
scaler = StandardScaler()

In [17]:
scaler.fit(df.drop('time_in_hospital', axis=1))

StandardScaler(copy=True, with_mean=True, with_std=True)

In [18]:
scaled_features = scaler.transform(df.drop('time_in_hospital', axis=1))

In [19]:
df_feat = pd.DataFrame(scaled_features, columns=df.columns[:-1])
df_feat.head()

        age  time_in_hospital  ...  num_medications  number_emergency
0  5.032990         -0.106517  ...         -0.21262         -3.321596
1  3.167431          0.808384  ...         -0.21262          0.815784
2  2.545578         -1.631351  ...         -0.21262         -0.735733
3  1.923725          0.045967  ...         -0.21262         -0.218561
4  1.301873          0.401761  ...         -0.21262         -1.252906

[5 rows x 6 columns]

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
X_train, X_test, y_train, y_test = train_test_split(scaled_features,df['age'],test_size=0.30)

In [22]:
from sklearn.neighbors import KNeighborsClassifier

In [23]:
knn = KNeighborsClassifier(n_neighbors=1)

In [24]:
knn.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

In [25]:
pred = knn.predict(X_test)

In [26]:
from sklearn.metrics import classification_report,confusion_matrix

In [27]:
print(confusion_matrix(y_test,pred))

[[ 826   22    0    0    0    0    0    0    0    0]
 [   1 5164   36    1    0    0    0    0    0    0]
 [   0   12 7873   36    0    0    1    0    0    0]
 [   0    0   28 6536   25    1    0    0    0    0]
 [   0    0    0   26 5130   25    0    0    0    0]
 [   0    0    0    0   49 2801   15    0    0    0]
 [   0    0    0    1    2   50 1103   12    0    0]
 [   0    0    0    0    0    0   46  444    2    0]
 [   0    0    0    0    0    0    1   20  192    0]
 [   0    0    0    0    0    0    0    0    1   48]]

In [28]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

        -100       1.00      0.97      0.99       848
         -90       0.99      0.99      0.99      5202
         -80       0.99      0.99      0.99      7922
         -70       0.99      0.99      0.99      6590
         -60       0.99      0.99      0.99      5181
         -50       0.97      0.98      0.98      2865
         -40       0.95      0.94      0.95      1168
         -30       0.93      0.90      0.92       492
         -20       0.98      0.90      0.94       213
          10       1.00      0.98      0.99        49

    accuracy                           0.99     30530
   macro avg       0.98      0.96      0.97     30530
weighted avg       0.99      0.99      0.99     30530

In [29]:
error_rate = []

for i in range(1,40):

  knn = KNeighborsClassifier(n_neighbors=i)
  knn.fit(X_train,y_train)
  pred_i = knn.predict(X_test)
  error_rate.append(np.mean(pred_i != y_test))

plt.figure(figsize=(10,6))
plt.plot(range(1,40), error_rate,color='blue', linestyle='dashed', marker='o',
          markerfacecolor='red',markersize=10)
plt.title('Error Rate vs. K Value')
plt.xlabel('K')
plt.ylabel('Error Rate')

KeyboardInterrupt: ignored